# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

Name:           convert2json
Version:        1.1.4
Release:        %autorelease
Summary:        Utilities to convert CSV, INI, RSV, TOML, XML & YAML into JSON

License:        MIT
URL:            https://github.com/simonrupf/convert2json
Source0:        https://github.com/simonrupf/convert2json/archive/%{version}/convert2json-%{version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 26
Requires:       jq

%global _description %{expand:
Command line utilities to convert CSV, INI, RSV, TOML, XML & YAML into JSON and
for use with jaq or jq.}

%description %{_description}

%prep
%autosetup -n convert2json-%{version} -p1
%cargo_prep -n -f csv,toml,xml

%generate_buildrequires
%cargo_generate_buildrequires -n -f csv,toml,xml

%build
%cargo_build -n -f csv,toml,xml
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install -n -f csv,toml,xml

%if %{with check}
%check
%cargo_test -n -f csv,toml,xml
%endif

%files
%license LICENSE-MIT
%license LICENSE.md
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc README.md
%{_bindir}/cq
%{_bindir}/csv2json
%{_bindir}/toml2json
%{_bindir}/tq
%{_bindir}/xml2json
%{_bindir}/xq

%changelog
%autochangelog
