# Generated by rust2rpm 27
%bcond check 1

%global crate convert2json

Name:           convert2json
Version:        1.1.4
Release:        %autorelease
Summary:        CLI utilities to convert CSV, INI, RSV, TOML, XML & YAML into JSON and for use with jaq or jq

License:        MIT
URL:            https://crates.io/crates/convert2json
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
CLI utilities to convert CSV, INI, RSV, TOML, XML & YAML into JSON and
for use with jaq or jq.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
License:        MIT
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}
Requires:       jq

%files       -n %{crate}
%license LICENSE-MIT
%license LICENSE.md
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc README.md
%{_bindir}/cq
%{_bindir}/csv2json
%{_bindir}/ini2json
%{_bindir}/iq
%{_bindir}/rq
%{_bindir}/rsv2json
%{_bindir}/toml2json
%{_bindir}/tq
%{_bindir}/xml2json
%{_bindir}/xq
%{_bindir}/yaml2json
%{_bindir}/yq

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
