name: Rust test & lint
on:
  push:
    branches: '*'
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.70.0
        override: true
        components: rustfmt, clippy
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    - name: Execute all unit and integration tests and build examples
      uses: actions-rs/cargo@v1
      with:
        command: test
    - name: Check formatting of code and suggest improvements
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: Check for common mistakes and code improvements
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
